version: '3.8'
services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/site_docker
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14.0
    environment:
      POSTGRES_DB: cookbook
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432